### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [IndaPlus22/alww-task-5#1]
**With lots to ask for well done Albin!**

YOU ARE THE FRICKING FIRST!

#### Structure Exercises like Instructed
You are instructed to organise your Java code in two files: `SetTheory.java` and `Arrays.java`. Please organise your Rust code in two modules: `set_theory.rs` and `arrays.rs`.

#### Complete All Tasks
I cannot find your solution to task _Exercise 5.6 -- SetTheory.java and generateSet_.

#### Reading Comprehension Way Beyond Balmer
The instructions:
> Your task at hand is now to model mathematical sets with `ArrayLists`. A set is defined as having unique elements. For example, `{1, 2, 2, 3}` is not a set, whereas `{1, 2, 3}` is a set. It is up to your implementations to guarantee this assumption.

Why then are you using `HashSet`? Your function headers:

```rs
fn union(mut a: HashSet<usize>, b: HashSet<usize>) -> HashSet<usize>
```
```rs
fn intersect(a: HashSet<usize>, b: HashSet<usize>) -> HashSet<usize>
```
```rs
fn complement(mut a: HashSet<usize>, b: HashSet<usize>) -> HashSet<usize>
```
```rs
fn cardinality_of_union(mut a: HashSet<usize>, b: HashSet<usize>) -> usize
```
```rs
fn cardinality(a: HashSet<usize>) -> usize
```

#### Fix Data Struction Sizing
I can take crap, but man, Java arrays are dynamically sized; Java arrays _do not_ have a static sizing of `4` elements.

```rs
fn average_of_array(array: [usize; 4]) -> u8
```
```rs
fn average_of_array_double(array: [usize; 4]) -> f32
```
```rs
fn smallest_element_of_array(array: [usize; 4]) -> usize
```
```rs
fn reverse(array: [usize; 4]) -> [usize; 4]
```
```rs
fn return_even(array: [usize; 4]) -> Vec<usize>
```

This is a lazy solution.

Java arrays are dynamically sized and heap allocated. Rust arrays are statically sized and stack allocated. Therefore, you have an argument to choose `Vec` as a translation of Java arrays.

##### Exercise 5.3 -- Smallest element of an array
Are you trolling me??? You should be thankful that `array.len() == 4`.

_Your code_:
```rs
use std::{cmp, /*...*/};

//...

fn smallest_element_of_array(array: [usize; 4]) -> usize {
    return return_smallest(
        &return_smallest(&array[2], &array[3]),
        &return_smallest(&array[0], &array[1]),
    );
}
fn return_smallest(a: &usize, b: &usize) -> usize {
    match a.cmp(b) {
        cmp::Ordering::Less => return a.clone(),
        cmp::Ordering::Greater => return b.clone(),
        cmp::Ordering::Equal => return a.clone(),
    }
}
```
_Suggestion_:
```rs
fn smallest_element_of_array(array: [usize; 4]) -> usize {
    array[0].min(array[1]).min(array[2]).min(array[3])
}
```

##### Exercise 5.4 -- Reverse
Again???! You should be thankful that `array.len() == 4`.

_Your code_:
```rs
fn reverse(array: [usize; 4]) -> [usize; 4] {
    return [array[3], array[2], array[1], array[0]];
}
```

##### Exercise 5.5 -- Return all even numbers in an array
Sooooo NOW YOU SEE THE ISSUE aT *H*an**D**??!

#### Missing Borrows
Java complex data types (reference types) are passed-by-reference. Rust values are passed-by-ownership accoring to RAII-based ownership system. Therefore, I suggest you borrow your parameters when suitable.

#### Empty Classes

The Java `Arrays` class only containes static methods, thus could be represented by the empty Rust struct `Arrays`.

##### Integers

You choose (at most times) to translate the Java primitive type `int` to Rust `usize`. They are not guaranteed to have the same byte size, nor do they share signage (`int` is signed while `usize` is unsigned).

A more fitting type translation would be to Rust `i32`.

##### Floating Point Numbers
A Java primitive type `double` is twice as large as the Rust `f32`, whaaaa....

##### Data Types
What did you think when translating the Java `int` to Rust `u8` and `usize`???

_Instruction method header_:
```java
public static int average(int[] array)
```

_Your function header_:
```rs
fn average_of_array(array: [usize; /*...*/]) -> u8
```

##### Logic
Rust sad noises...

_Your code_:
```rs
fn average_of_array(array: /*...*/) -> u8 {
    let mut sum = 0;
    for x in array {
        sum += x;
    }
    return (sum / array.len()).try_into().unwrap();
}
```
_Suggestion_:
```rs
fn average_of_array(array: /*...*/) -> u8 {
    let sum = array.iter().sum::<usize>();
    return (sum / array.len()) as u8;
}
```

#### Exercise 5.2 -- Average of an array... again?
You return a rounded down value, which I don't think is the case.

_Your code_:
```rs
fn average_of_array_double(array: [usize; /*...*/]) -> f32 {
    //...
    return (sum / array.len()) as f32;
}
```
_Suggestion_:
```rs
fn average_of_array_double(array: [usize; /*...*/]) -> f32 {
    //...
    return sum as f32 / array.len() as f32;
}
```

Also, observe the template Java method header:
> ```java
> public static double average(double[] array)
> ```

When did floating point numbers become integer types??????

#### Exercise 5.5 -- Return all even numbers in an array
Rust sad noises...

_Your code_:
```rs
fn return_even(array: [usize; 4]) -> Vec<usize> {
    let mut v: Vec<usize> = Vec::new();
    for x in array {
        match x % 2 {
            0 => v.push(x),
            _ => continue,
        }
    }
    v
}
```
_Suggestion_:
```rs
fn return_even(array: [usize; 4]) -> Vec<usize> {
    array
        .iter()
        .filter(|x| x % 2)
        .collext::<Vec<usize>>()
}
```

#### Exercise 5.9 -- complement
Imperative control flow structures take lines and requires mutability. Notwithregarding you insistence of multiple reallocations due to the lack of pre-allocation. 

Also, you forget `99`, what has `99` ever done to you?

_Your code_:
```rs
let mut c: HashSet<usize> = HashSet::new();
for x in 0..99 {
    c.insert(x);
}
```
_Suggestion_:
```rs
let c: HashSet<usize> = (0..=99).collect();
```

### Corrections of Instructions

Observe the instruction:

> #### Exercise 5.3 -- Smallest element of an array
> Write a method that returns the smallest element of an array. It must have the following header:
> 
> ```java
> public static int smallestElement(int[] array)
> ```

The naming convention for this kind of method is `min`.

**Keep up the good work!**

**Comment by Trollkaaar** [comment]
(⁄ ⁄•⁄ω⁄•⁄ ⁄)
should be fine now

**Comment by violaso** [comment]
I like how you somehow find it reasonable to convert vectors into hashsets to access standard library functions, but don't use a similar method with functions as `smallest_element_of_array`.

_Your code_:
```rs
pub fn smallest_element_of_array(array: &Vec<isize>) -> isize {
    let mut smallest: isize = array[0];
    for x in array {
        if (*x < smallest) {
            smallest = *x;
        }
    }
    return smallest;
}
```

_Suggestion_:
```rs
pub fn smallest_element_of_array(array: &Vec<isize>) -> isize {
    array.iter().min::<isize>()
}
```
